global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'db-extractor'
    static_configs:
      - targets: ['db-extractor:8000']
  - job_name: 'stream-processor'
    static_configs:
      - targets: ['stream-processor:8000']
